repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v1.2.3
        hooks:
            -   id: trailing-whitespace
                name: Trim Trailing Whitespace
                description: This hook trims trailing whitespace
            -   id: end-of-file-fixer
                name: End of File Fixer
                description: Makes sure files end in a newline and only newline
            -   id: detect-private-key
                name: Detect Private Key
                description: Checks for the existence of private keys
#    -   repo: git://github.com/awebdeveloper/pre-commit-tslint/
#        rev: v0.0.2
#        hooks:
#            -   id: tslint
#                name: tslint
#                entry: tslint
#                language: node
#                files: \.(ts)$
#                args: []
